In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r'C:\Users\kunal bondla\OneDrive\Desktop\try\deeplearning\Data\new_insurance_data.csv')

In [5]:

X = df[['age', 'affordibility']].values
y = df[['bought_insurance']].values

In [6]:
X[:, 0] = X[:, 0] / 100  # Normalize the 'age' column

In [7]:
X = np.hstack((np.ones((X.shape[0], 1)), X))  # Add bias term as the first column

In [8]:
# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Binary cross-entropy loss
def compute_loss(y, y_pred):
    return -np.mean(y * np.log(y_pred) + (1 - y) * np.log(1 - y_pred))

def gradient_descent(X, y, lr=0.1, epochs=100):
    m, n = X.shape  # m: number of samples, n: number of features (including bias)
    weights = np.zeros(n).reshape(-1, 1)  # Initialize weights to zeros (n, 1)
    losses = []

    # Ensure y is reshaped correctly
    y = y.reshape(-1, 1)

    for epoch in range(epochs):
        # Linear combination
        z = np.dot(X, weights)  # Shape: (m, 1)
        # Sigmoid activation
        y_pred = 1 / (1 + np.exp(-z))  # Shape: (m, 1)
        # Compute gradient
        gradient = np.dot(X.T, (y_pred - y)) / m  # Shape: (n, 1)
        # Update weights
        weights -= lr * gradient
        # Compute loss
        loss = -np.mean(y * np.log(y_pred) + (1 - y) * np.log(1 - y_pred))  # Binary cross-entropy loss
        losses.append(loss)

        # Print progress every 10 epochs
        if epoch % 10 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return weights, losses

In [9]:
# Run gradient descent
learning_rate = 0.1
epochs = 100
weights, losses = gradient_descent(X, y, lr=learning_rate, epochs=epochs)

# Print final weights
print("Trained Weights (including bias):", weights)

Epoch 0, Loss: 0.6931
Epoch 10, Loss: 0.6862
Epoch 20, Loss: 0.6808
Epoch 30, Loss: 0.6763
Epoch 40, Loss: 0.6722
Epoch 50, Loss: 0.6685
Epoch 60, Loss: 0.6652
Epoch 70, Loss: 0.6621
Epoch 80, Loss: 0.6592
Epoch 90, Loss: 0.6565
Trained Weights (including bias): [[-0.25495847]
 [ 0.        ]
 [ 0.55159276]]


In [10]:
# Calculate predictions
z = np.dot(X, weights)
y_pred = sigmoid(z)
y_pred_classes = (y_pred >= 0.5).astype(int)  # Convert probabilities to binary predictions

# Calculate accuracy
accuracy = np.mean(y_pred_classes == y)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.6786


In [11]:
y_predicted = np.array(y_pred_classes)
y_true = np.array(y)

In [12]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [13]:
mae(y_predicted, y_true)

Total error is: [9]
Mean absolute error is: [0.32142857]


array([0.32142857])

In [14]:
np.abs(y_predicted-y_true)

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1]])

In [15]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [16]:
mae_np(y_predicted, y_true)

np.float64(0.32142857142857145)

In [17]:
np.log([0])

C:\Users\kunal bondla\AppData\Local\Temp\ipykernel_16236\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [18]:
epsilon = 1e-15

In [19]:
np.log([1e-15])

array([-34.53877639])

In [20]:
y_predicted

array([[1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [21]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[array([1]),
 1e-15,
 array([1]),
 1e-15,
 array([1]),
 array([1]),
 1e-15,
 1e-15,
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 1e-15,
 1e-15,
 array([1]),
 array([1]),
 1e-15,
 array([1]),
 1e-15,
 array([1]),
 array([1]),
 1e-15,
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1])]

In [22]:
1-epsilon

0.999999999999999

In [23]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e-15, 1.e+00, 1.e-15, 1.e+00, 1.e+00, 1.e-15, 1.e-15,
       1.e+00, 1.e+00, 1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00, 1.e+00,
       1.e-15, 1.e+00, 1.e-15, 1.e+00, 1.e+00, 1.e-15, 1.e+00, 1.e+00,
       1.e+00, 1.e+00, 1.e+00, 1.e+00])

In [24]:
np.log(y_predicted_new)

array([-9.99200722e-16, -3.45387764e+01, -9.99200722e-16, -3.45387764e+01,
       -9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16, -9.99200722e-16, -9.99200722e-16, -9.99200722e-16,
       -3.45387764e+01, -3.45387764e+01, -9.99200722e-16, -9.99200722e-16,
       -3.45387764e+01, -9.99200722e-16, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16, -3.45387764e+01, -9.99200722e-16, -9.99200722e-16,
       -9.99200722e-16, -9.99200722e-16, -9.99200722e-16, -9.99200722e-16])

In [25]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.26965948944059)

In [26]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [27]:
log_loss(y_true, y_predicted)

np.float64(17.26965948944059)